version: '1'
services:
  app:
    build:
      context: .
      args:
        - MODE=dev
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    container_name: appcontainer
    ports:
    - "8000:8000"